//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 12:00:46 PM CET 
//


package es.rickyepoderi.spml4jaxb.test.clone;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dsml.spml.ddbb.user.clone package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CloneRequestType_QNAME = new QName("urn:ddbb-spml-dsml:user:clone", "cloneRequestType");
    private final static QName _CloneResponseType_QNAME = new QName("urn:ddbb-spml-dsml:user:clone", "cloneResponseType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dsml.spml.ddbb.user.clone
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CloneRequestType }
     * 
     */
    public CloneRequestType createCloneRequestType() {
        return new CloneRequestType();
    }

    /**
     * Create an instance of {@link CloneResponseType }
     * 
     */
    public CloneResponseType createCloneResponseType() {
        return new CloneResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloneRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ddbb-spml-dsml:user:clone", name = "cloneRequestType")
    public JAXBElement<CloneRequestType> createCloneRequestType(CloneRequestType value) {
        return new JAXBElement<CloneRequestType>(_CloneRequestType_QNAME, CloneRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloneResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ddbb-spml-dsml:user:clone", name = "cloneResponseType")
    public JAXBElement<CloneResponseType> createCloneResponseType(CloneResponseType value) {
        return new JAXBElement<CloneResponseType>(_CloneResponseType_QNAME, CloneResponseType.class, null, value);
    }

}
