//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 12:00:46 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn:ddbb-spml-dsml:user:clone", 
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
            @XmlNs(prefix = "clone", namespaceURI = "urn:ddbb-spml-dsml:user:clone")
        }
)
package es.rickyepoderi.spml4jaxb.test.clone;

import javax.xml.bind.annotation.XmlNs;

