//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.31 at 07:40:23 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn:oasis:names:tc:SPML:2:0:search", 
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
            @XmlNs(prefix = "spmlsearch", namespaceURI = "urn:oasis:names:tc:SPML:2:0:search")
        }
)
package es.rickyepoderi.spml4jaxb.msg.search;

import javax.xml.bind.annotation.XmlNs;
