//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.24 at 02:52:06 PM CEST 
//


package es.rickyepoderi.spml4jaxb.msg.spmldsml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.tc.spml._2._0.dsml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Schema_QNAME = new QName("urn:oasis:names:tc:SPML:2:0:DSML", "schema");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.tc.spml._2._0.dsml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SchemaType }
     * 
     */
    public SchemaType createSchemaType() {
        return new SchemaType();
    }

    /**
     * Create an instance of {@link ObjectClassDefinitionType }
     * 
     */
    public ObjectClassDefinitionType createObjectClassDefinitionType() {
        return new ObjectClassDefinitionType();
    }

    /**
     * Create an instance of {@link AttributeDefinitionReferenceType }
     * 
     */
    public AttributeDefinitionReferenceType createAttributeDefinitionReferenceType() {
        return new AttributeDefinitionReferenceType();
    }

    /**
     * Create an instance of {@link ObjectClassDefinitionReferenceType }
     * 
     */
    public ObjectClassDefinitionReferenceType createObjectClassDefinitionReferenceType() {
        return new ObjectClassDefinitionReferenceType();
    }

    /**
     * Create an instance of {@link AttributeDefinitionReferencesType }
     * 
     */
    public AttributeDefinitionReferencesType createAttributeDefinitionReferencesType() {
        return new AttributeDefinitionReferencesType();
    }

    /**
     * Create an instance of {@link ObjectClassDefinitionReferencesType }
     * 
     */
    public ObjectClassDefinitionReferencesType createObjectClassDefinitionReferencesType() {
        return new ObjectClassDefinitionReferencesType();
    }

    /**
     * Create an instance of {@link AttributeDefinitionType }
     * 
     */
    public AttributeDefinitionType createAttributeDefinitionType() {
        return new AttributeDefinitionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchemaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SPML:2:0:DSML", name = "schema")
    public JAXBElement<SchemaType> createSchema(SchemaType value) {
        return new JAXBElement<SchemaType>(_Schema_QNAME, SchemaType.class, null, value);
    }

}
