//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.24 at 02:52:06 PM CEST 
//


package es.rickyepoderi.spml4jaxb.msg.spmldsml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import es.rickyepoderi.spml4jaxb.msg.core.ExtensibleType;


/**
 * <p>Java class for SchemaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchemaType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oasis:names:tc:SPML:2:0}ExtensibleType">
 *       &lt;sequence>
 *         &lt;element name="objectClassDefinition" type="{urn:oasis:names:tc:SPML:2:0:DSML}ObjectClassDefinitionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="attributeDefinition" type="{urn:oasis:names:tc:SPML:2:0:DSML}AttributeDefinitionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace=''/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchemaType", propOrder = {
    "objectClassDefinition",
    "attributeDefinition"
})
public class SchemaType
    extends ExtensibleType
{

    protected List<ObjectClassDefinitionType> objectClassDefinition;
    protected List<AttributeDefinitionType> attributeDefinition;

    /**
     * Gets the value of the objectClassDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectClassDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectClassDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectClassDefinitionType }
     * 
     * 
     */
    public List<ObjectClassDefinitionType> getObjectClassDefinition() {
        if (objectClassDefinition == null) {
            objectClassDefinition = new ArrayList<ObjectClassDefinitionType>();
        }
        return this.objectClassDefinition;
    }

    /**
     * Gets the value of the attributeDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeDefinitionType }
     * 
     * 
     */
    public List<AttributeDefinitionType> getAttributeDefinition() {
        if (attributeDefinition == null) {
            attributeDefinition = new ArrayList<AttributeDefinitionType>();
        }
        return this.attributeDefinition;
    }

}
