//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.30 at 07:01:11 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn:oasis:names:tc:SPML:2:0:password", 
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
            @XmlNs(prefix = "spmlpass", namespaceURI = "urn:oasis:names:tc:SPML:2:0:password")
        }
)
package es.rickyepoderi.spml4jaxb.msg.password;

import javax.xml.bind.annotation.XmlNs;