//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.29 at 11:43:28 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn:oasis:names:tc:SPML:2:0:async",
        xmlns = {
            @XmlNs(prefix = "spmlasync", namespaceURI = "urn:oasis:names:tc:SPML:2:0:async")
        })
package es.rickyepoderi.spml4jaxb.msg.async;

import javax.xml.bind.annotation.XmlNs;

