//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 11:44:53 AM CEST 
//


package es.rickyepoderi.spml4jaxb.msg.batch;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OnErrorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OnErrorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="resume"/>
 *     &lt;enumeration value="exit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OnErrorType")
@XmlEnum
public enum OnErrorType {

    @XmlEnumValue("resume")
    RESUME("resume"),
    @XmlEnumValue("exit")
    EXIT("exit");
    private final String value;

    OnErrorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OnErrorType fromValue(String v) {
        for (OnErrorType c: OnErrorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
