//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 11:44:53 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn:oasis:names:tc:SPML:2:0:batch",
        xmlns = {
            @XmlNs(prefix = "spmlbatch", namespaceURI = "urn:oasis:names:tc:SPML:2:0:batch")
        }
)
package es.rickyepoderi.spml4jaxb.msg.batch;

import javax.xml.bind.annotation.XmlNs;

