//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 03:06:08 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn:oasis:names:tc:SPML:2:0:reference", 
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
            @XmlNs(prefix = "spmlref", namespaceURI = "urn:oasis:names:tc:SPML:2:0:reference")
        }
)
package es.rickyepoderi.spml4jaxb.msg.reference;

import javax.xml.bind.annotation.XmlNs;