/* 
 * Copyright (c) 2015 ricky <https://github.com/rickyepoderi/spml4jaxb>
 * 
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  See the file COPYING included with this distribution for more
 *  information.
 */
package es.rickyepoderi.spml4jaxb.accessor;

import es.rickyepoderi.spml4jaxb.builder.ExpirePasswordRequestBuilder;
import es.rickyepoderi.spml4jaxb.builder.RequestBuilder;
import es.rickyepoderi.spml4jaxb.builder.ResponseBuilder;
import es.rickyepoderi.spml4jaxb.msg.password.ExpirePasswordRequestType;

/**
 * <p>Accessor for the SPMLv2 ExpirePassword operation request. The ExpirePassword
 * operation is defined inside the password capability (capability to perform
 * password management). The ExpirePassword method is used to expire a user
 * password (the standard gives the possibility of giving some extra tries).</p>
 * 
 * @author ricky
 */
public class ExpirePasswordRequestAccessor extends BaseRequestAccessor<ExpirePasswordRequestType, 
        ExpirePasswordRequestAccessor, ExpirePasswordRequestBuilder> {

    /**
     * Constructor for a an empty ExpirePassword request accessor.
     */
    protected ExpirePasswordRequestAccessor() {
        this(new ExpirePasswordRequestType());
    }
    
    /**
     * Constructor for a ExpirePassword request accessor giving the internal type.
     * @param request The internal ExpirePassword request type as generated by JAXB
     */
    protected ExpirePasswordRequestAccessor(ExpirePasswordRequestType request) {
        super(request, request.getPsoID(), null);
    }
    
    /**
     * Getter for the remaining loggings tries to set to the user.
     * @return The remaining loggings set in the request
     */
    public int getRemainingLoggings() {
        return request.getRemainingLogins();
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public ResponseBuilder responseBuilder() {
        return ResponseBuilder.builderForExpirePassword();
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public ExpirePasswordRequestBuilder toBuilder() {
        return RequestBuilder.builderForExpirePassword().fromRequest(this.request);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExpirePasswordRequestAccessor asAccessor(ExpirePasswordRequestType request) {
        return new ExpirePasswordRequestAccessor(request);
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        String nl = System.getProperty("line.separator");
        StringBuilder sb = new StringBuilder(super.toString());
        sb.append("  remainingLogins: ").append(getRemainingLoggings()).append(nl);
        return sb.toString();
    }
    
}
