/* 
 * Copyright (c) 2015 ricky <https://github.com/rickyepoderi/spml4jaxb>
 * 
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  See the file COPYING included with this distribution for more
 *  information.
 */
package es.rickyepoderi.spml4jaxb.accessor;

import es.rickyepoderi.spml4jaxb.builder.ExpirePasswordResponseBuilder;
import es.rickyepoderi.spml4jaxb.builder.ResponseBuilder;
import es.rickyepoderi.spml4jaxb.msg.core.ResponseType;

/**
 * <p>Accessor for the SPMLv2 ExpirePassword operation response. The ExpirePassword
 * operation is defined inside the password capability (capability to perform
 * password management). The ExpirePassword method is used to expire a user
 * password. The response has no extra properties.</p>
 * 
 * @author ricky
 */
public class ExpirePasswordResponseAccessor extends BaseResponseAccessor<ResponseType, ExpirePasswordResponseAccessor, ExpirePasswordResponseBuilder> {

    /**
     * Constructor for an empty ExpirePassword response accessor.
     */
    protected ExpirePasswordResponseAccessor() {
        this(new ResponseType());
    }
    
    /**
     * Constructor for an ExpirePassword response accessor giving the internal type.
     * @param response The internal ExpirePassword type generated by JAXB
     */
    protected ExpirePasswordResponseAccessor(ResponseType response) {
        super(response, null);
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public ExpirePasswordResponseBuilder toBuilder() {
        return ResponseBuilder.builderForExpirePassword().fromResponse(this.response);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExpirePasswordResponseAccessor asAccessor(ResponseType response) {
        return new ExpirePasswordResponseAccessor(response);
    }
    
}
