/* 
 * Copyright (c) 2015 ricky <https://github.com/rickyepoderi/spml4jaxb>
 * 
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  See the file COPYING included with this distribution for more
 *  information.
 */
package es.rickyepoderi.spml4jaxb.accessor;

import es.rickyepoderi.spml4jaxb.builder.FilterBuilder;
import es.rickyepoderi.spml4jaxb.msg.dsmlv2.AttributeDescription;
import es.rickyepoderi.spml4jaxb.msg.dsmlv2.AttributeValueAssertion;
import es.rickyepoderi.spml4jaxb.msg.dsmlv2.Filter;
import es.rickyepoderi.spml4jaxb.msg.dsmlv2.FilterSet;
import es.rickyepoderi.spml4jaxb.msg.dsmlv2.SubstringFilter;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;

/**
 * <p>This class is the accessor for filters. A filter is the object that the
 * SPMLv2 standard manages to specify a search over the server in the DSML profile. 
 * The filter manages attribute conditions very similar to the conditions
 * given in an LDAP query filter.</p>
 * 
 * @author ricky
 */
public class FilterAccessor implements Accessor<Filter, FilterAccessor, FilterBuilder>{
    
    /**
     * The internal filer that this accessor manages.
     */
    protected Filter filter;
    
    /**
     * Constructor of the accessor giving the internal filter.
     * @param filter The internal filter type as defined by XSD files (generated by JAXB)
     */
    public FilterAccessor(Filter filter) {
        this.filter = filter;
    }
    
    /**
     * Returns if the filter is a equals comparison.
     * @return true if equals, false if not
     */
    public boolean isEquals() {
        return filter.getEqualityMatch() != null;
    }
    
    /**
     * Returns the value assertion associated to a equals comparison.
     * @return The value assertion if it is a equals comparison, null if not
     */
    public AttributeValueAssertion getEquals() {
        if (isEquals()) {
            return filter.getEqualityMatch();
        } else {
            return null;
        }
    }
    
    /**
     * Returns if the filter is a greater or equals comparison.
     * @return true if greater or equals, false if not
     */
    public boolean isGreaterOrEqual() {
        return filter.getGreaterOrEqual() != null;
    }
    
    /**
     * Returns the filter associated to a greater or equal comparison.
     * @return The value assertion if it is a greater or equal comparison, null if not
     */
    public AttributeValueAssertion getGreaterOrEqual() {
        if (isGreaterOrEqual()) {
            return filter.getGreaterOrEqual();
        } else {
            return null;
        }
    }
    
    /**
     * Returns if the filter is a less or equals comparison.
     * @return true if less or equals, false if not
     */
    public boolean isLessOrEqual() {
        return filter.getLessOrEqual() != null;
    }
    
    /**
     * Returns the value assertion associated to a less or equal comparison.
     * @return The value assertion if it is a less or equal comparison, null if not
     */
    public AttributeValueAssertion getLessOrEqual() {
        if (isLessOrEqual()) {
            return filter.getLessOrEqual();
        } else {
            return null;
        }
    }
    
    /**
     * Returns if the filter is a approximation comparison.
     * @return true if approximation, false if not
     */
    public boolean isApproxMatch() {
        return filter.getApproxMatch() != null;
    }
    
    /**
     * Returns the value assertion associated to a greater or equal comparison.
     * @return The value assertion if it is a approximation comparison, null if not
     */
    public AttributeValueAssertion getApproxMatch() {
        if (isApproxMatch()) {
            return filter.getApproxMatch();
        } else {
            return null;
        }
    }
    
    /**
     * Returns if the filter is a present comparison.
     * @return true if present, false if not
     */
    public boolean isPresent() {
        return filter.getPresent()!= null;
    }
    
    /**
     * Returns the attribute description associated to a present comparison.
     * @return The attribute description if it is a approximation comparison, null if not
     */
    public AttributeDescription getPresent() {
        if (isPresent()) {
            return filter.getPresent();
        } else {
            return null;
        }
    }
    
   /**
     * Returns if the filter is a starts with comparison.
     * @return true if starts with, false if not
     */
     public boolean isStartsWith() {
        return filter.getSubstrings() != null && filter.getSubstrings().getInitial() != null;
    }
    
    /**
     * Returns the value assertion associated to a starts with comparison.
     * @return The value assertion if it is a starts with comparison, null if not
     */
    public AttributeValueAssertion getStartsWith() {
        if (isStartsWith()) {
            AttributeValueAssertion ava = new AttributeValueAssertion();
            ava.setName(filter.getSubstrings().getName());
            ava.setValue(filter.getSubstrings().getInitial());
            return ava;
        } else {
            return null;
        }
    }
    
    /**
     * Returns if the filter is a ends with comparison.
     * @return true if ends with, false if not
     */
    public boolean isEndsWith() {
        return filter.getSubstrings() != null && filter.getSubstrings().getFinal() != null;
    }
    
    /**
     * Returns the value assertion associated to an ends with comparison.
     * @return The value assertion if it is an ends with comparison, null if not
     */
    public AttributeValueAssertion getEndsWith() {
        if (isEndsWith()) {
            AttributeValueAssertion ava = new AttributeValueAssertion();
            ava.setName(filter.getSubstrings().getName());
            ava.setValue(filter.getSubstrings().getFinal());
            return ava;
        } else {
            return null;
        }
    }
    
    /**
     * Returns if the filter is a contains comparison.
     * @return true if contains, false if not
     */
    public boolean isContains() {
        return filter.getSubstrings() != null && !filter.getSubstrings().getAny().isEmpty();
    }
    
    /**
     * Returns the value assertion associated to a contains comparison.
     * @return The value assertion if it is a contains comparison, null if not
     */
    public AttributeValueAssertion getContains() {
        if (isContains()) {
            AttributeValueAssertion ava = new AttributeValueAssertion();
            ava.setName(filter.getSubstrings().getName());
            ava.setValue(filter.getSubstrings().getAny().get(0));
            return ava;
        } else {
            return null;
        }
    }
    
    /**
     * Returns if the filter is an and filter.
     * @return true if an and, false if not
     */
    public boolean isAnd() {
        return filter.getAnd() != null && !filter.getAnd().getFilterGroup().isEmpty();
    }
    
    /**
     * Returns the array of filter accessors that compounds an and filter.
     * @return The array of accessors if it is an and, null if not
     */
    public FilterAccessor[] getAnd() {
        if (isAnd()) {
            return getFilterSet(filter.getAnd());
        } else {
            return null;
        }
    }
    
    /**
     * Returns if the filter is an or filter.
     * @return true if an or, false if not
     */
    public boolean isOr() {
        return filter.getOr() != null && !filter.getOr().getFilterGroup().isEmpty();
    }
    
    /**
     * Returns the array of filter accessors that compounds an or filter.
     * @return The array of accessors if it is an or, null if not
     */
    public FilterAccessor[] getOr() {
        if (isOr()) {
            return getFilterSet(filter.getOr());
        } else {
            return null;
        }
    }
    
    /**
     * Returns if the filter is a not filter.
     * @return true if a not, false if not
     */
    public boolean isNot() {
        return filter.getNot() != null;
    }
    
    /**
     * Returns the accessor of a not filter.
     * @return The accessors of the not member if it is a not filter, null if not
     */
    public FilterAccessor getNot() {
        if (isNot()) {
            return new FilterAccessor(filter.getNot());
        } else {
            return null;
        }
    }
    
    /**
     * Method that return an array of filter accessor from a internal FilterSet.
     * This method is used by the and, or and not filter to obtain the list
     * of other accessors that compounds the filter.
     * 
     * @param fs The FilterSet to obtain the accessors from
     * @return The array of accessors or an empty array
     */
    public FilterAccessor[] getFilterSet(FilterSet fs) {
        List<JAXBElement<?>> list = fs.getFilterGroup();
        List<FilterAccessor> res = new ArrayList<>(list.size());
        for (JAXBElement<?> el: list) {
            if ("urn:oasis:names:tc:DSML:2:0:core".equals(el.getName().getNamespaceURI())) {
                if ("equalityMatch".equals(el.getName().getLocalPart())) {
                    Filter f = new Filter();
                    f.setEqualityMatch((AttributeValueAssertion) el.getValue());
                    res.add(new FilterAccessor(f));
                } else if ("greaterOrEqual".equals(el.getName().getLocalPart())) {
                    Filter f = new Filter();
                    f.setGreaterOrEqual((AttributeValueAssertion) el.getValue());
                    res.add(new FilterAccessor(f));
                } else if ("lessOrEqual".equals(el.getName().getLocalPart())) {
                    Filter f = new Filter();
                    f.setLessOrEqual((AttributeValueAssertion) el.getValue());
                    res.add(new FilterAccessor(f));
                } else if ("approxMatch".equals(el.getName().getLocalPart())) {
                    Filter f = new Filter();
                    f.setApproxMatch((AttributeValueAssertion) el.getValue());
                    res.add(new FilterAccessor(f));
                } else if ("present".equals(el.getName().getLocalPart())) {
                    Filter f = new Filter();
                    f.setPresent((AttributeDescription) el.getValue());
                    res.add(new FilterAccessor(f));
                } else if ("substrings".equals(el.getName().getLocalPart())) {
                    Filter f = new Filter();
                    f.setSubstrings((SubstringFilter) el.getValue());
                    res.add(new FilterAccessor(f));
                } else if ("and".equals(el.getName().getLocalPart())) {
                    Filter f = new Filter();
                    f.setAnd((FilterSet) el.getValue());
                    res.add(new FilterAccessor(f));
                } else if ("or".equals(el.getName().getLocalPart())) {
                    Filter f = new Filter();
                    f.setOr((FilterSet) el.getValue());
                    res.add(new FilterAccessor(f));
                }  else if ("not".equals(el.getName().getLocalPart())) {
                    Filter f = new Filter();
                    f.setNot((Filter) el.getValue());
                    res.add(new FilterAccessor(f));
                }
            }
        }
        return res.toArray(new FilterAccessor[0]);
    }
    
    /**
     * String representation of the filter. This string representation uses an
     * ldap syntax to reprsent the filter.
     * @return The string representation of the filter using ldap format
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        if (isEquals()) {
            AttributeValueAssertion a = getEquals();
            sb.append("(").append(a.getName()).append("=").append(a.getValue()).append(")");
        } else if (isGreaterOrEqual()) {
            AttributeValueAssertion a = getGreaterOrEqual();
            sb.append("(").append(a.getName()).append(">=").append(a.getValue()).append(")");
        } else if (isLessOrEqual()) {
            AttributeValueAssertion a = getLessOrEqual();
            sb.append("(").append(a.getName()).append("<=").append(a.getValue()).append(")");
        } else if (isApproxMatch()) {
            AttributeValueAssertion a = getApproxMatch();
            sb.append("(").append(a.getName()).append("=~").append(a.getValue()).append(")");
        } else if (isPresent()) {
            AttributeDescription a = getPresent();
            sb.append("(").append(a.getName()).append("=*").append(")");
        } else if (isStartsWith()) {
            AttributeValueAssertion a = getStartsWith();
            sb.append("(").append(a.getName()).append("=").append(a.getValue()).append("*)");
        } else if (isEndsWith()) {
            AttributeValueAssertion a = getEndsWith();
            sb.append("(").append(a.getName()).append("=*").append(a.getValue()).append(")");
        } else if (isContains()) {
            AttributeValueAssertion a = getContains();
            sb.append("(").append(a.getName()).append("=*").append(a.getValue()).append("*)");
        } else if (isNot()) {
            sb.append("(!").append(getNot()).append(")");
        } else if (isAnd()) {
            sb.append("(&");
            for (FilterAccessor f: getAnd()) {
                sb.append(f);
            }
            sb.append(")");
        } else if (isOr()) {
            sb.append("(|");
            for (FilterAccessor f: getOr()) {
                sb.append(f);
            }
            sb.append(")");
        } else {
            throw new IllegalStateException("Invalid filter!!!");
        }
        return sb.toString();
    }

    @Override
    public Filter getInternalType() {
        return this.filter;
    }

    @Override
    public FilterBuilder toBuilder() {
        return new FilterBuilder(filter);
    }

    @Override
    public FilterAccessor asAccessor(Filter type) {
        return new FilterAccessor(type);
    }
}
