/* 
 * Copyright (c) 2015 ricky <https://github.com/rickyepoderi/spml4jaxb>
 * 
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  See the file COPYING included with this distribution for more
 *  information.
 */
package es.rickyepoderi.spml4jaxb.accessor;

import es.rickyepoderi.spml4jaxb.builder.ListTargetsRequestBuilder;
import es.rickyepoderi.spml4jaxb.builder.RequestBuilder;
import es.rickyepoderi.spml4jaxb.builder.ResponseBuilder;
import es.rickyepoderi.spml4jaxb.msg.core.ListTargetsRequestType;

/**
 * <p>Accessor for the ListTargets request. The ListTargets operation is a function 
 * in the core capability as defined in SPMLv2. This operation is the first
 * operation that a client should send to a SPMLv2 server. The response gives
 * information about the SPMLv2 server, mainly the server manages one or more
 * targets. Each target represents a repository of objects to be managed
 * using SPMLv2. The ListTargets response returns the targets the server
 * manages and information about each one:</p>
 * 
 * <ol>
 * <li>The target should follow a profile. The profile describes how the data
 * should be represented inside the target. SPMLv2 defines two profiles:
 * XSD (data is managed using XML information based on a custom XSD file) and
 * DSML (data is managed using attributes more or less like in an LDAP 
 * repository).</li>
 * <li>The target should contain the schema of the data managed. In XSD profile
 * the schema is the XSD definition file of the interchanged objects. In DSML
 * profile the schema is the list of attributes and types of objects managed
 * (similar to objectclasses and attributes in an LDAP server).</li>
 * <li>Finally the list of capabilities supported by the target are exposed in
 * the response. SPMLv2 groups operations in different capabilities (the core
 * capability -CRUD- should be implemented by all SPMLv2 compatible servers but 
 * the rest of them are optional and only needed to cover more specific 
 * characteristics), the target information should inform what optional
 * capabilities are supported.</li>
 * </ol>
 * 
 * <p>The idea of the ListTargets is giving enough information about the target(s)
 * in the server to permit an easy access to the client. That is the reason why
 * this operation should be the first one requested by a client. Some servers
 * implementations (for the previous reason) extends the functionality of the
 * ListTargets method to perform a login.</p>
 * 
 * <p>The ListTargets information is quite complicated in the response but
 * simple in the request. In the request there is only one property just to
 * inform if the client requests for a specific profile targets.</p>
 * 
 * @author ricky
 */
public class ListTargetsRequestAccessor extends BaseRequestAccessor<ListTargetsRequestType, ListTargetsRequestAccessor, ListTargetsRequestBuilder> {

    /**
     * Constructor for an empty ListTargets requests accessor.
     */
    protected ListTargetsRequestAccessor() {
        this(new ListTargetsRequestType());
    }
    
    /**
     * Constructor for a ListTargets request accessor based on the internal type.
     * @param request The internal ListTargets request type generated by JAXB
     */
    protected ListTargetsRequestAccessor(ListTargetsRequestType request) {
        super(request, null, null);
    }
    
    /**
     * Getter for the profile the request is specifying. If null all the
     * targets (no matter the profile) should be returned by the server.
     * @return The URI of the profile requested
     */
    public String getProfile() {
        return request.getProfile();
    }
    
    /**
     * Check if the profile is set to DSML profile.
     * @return true if the profile in the request id the DSML uri, false otherwise
     */
    public boolean isDsml() {
        return ListTargetsRequestBuilder.DSML_PROFILE_URI.equals(request.getProfile());
    }
    
    /**
     * Check if the profile is set to XSD profile.
     * @return true if the profile in the request id the XSD uri, false otherwise
     */
    public boolean isXsd() {
        return ListTargetsRequestBuilder.XSD_PROFILE_URI.equals(request.getProfile());
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public ResponseBuilder responseBuilder() {
        return ResponseBuilder.builderForListTargets();
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public ListTargetsRequestBuilder toBuilder() {
        return RequestBuilder.builderForListTargets().fromRequest(this.request);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ListTargetsRequestAccessor asAccessor(ListTargetsRequestType request) {
        return new ListTargetsRequestAccessor(request);
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        String nl = System.getProperty("line.separator");
        StringBuilder sb = new StringBuilder();
        return sb.append(super.toString())
                .append("  profile: ").append(getProfile()).append(nl).toString();
    }
    
}