/* 
 * Copyright (c) 2015 ricky <https://github.com/rickyepoderi/spml4jaxb>
 * 
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  See the file COPYING included with this distribution for more
 *  information.
 */
package es.rickyepoderi.spml4jaxb.accessor;

import es.rickyepoderi.spml4jaxb.builder.ModifyResponseBuilder;
import es.rickyepoderi.spml4jaxb.builder.ResponseBuilder;
import es.rickyepoderi.spml4jaxb.msg.core.ModifyResponseType;

/**
 * <p>Accessor for the modify response. The modify operation is a function in the core
 * capability as defined in SPMLv2. This method modifies an existing object from
 * the target. The response has no special properties because it just manages 
 * the return data whose methods are inherited from the base response accessor.</p>
 * 
 * @author ricky
 */
public class ModifyResponseAccessor extends BaseResponseAccessor<ModifyResponseType, ModifyResponseAccessor, ModifyResponseBuilder> {

    /**
     * Constructor for an empty modify response accessor.
     */
    protected ModifyResponseAccessor() {
        this(new ModifyResponseType());
    }
    
    /**
     * Constructor for a modify response accessor using the internal type.
     * @param response The internal modify response type generated by JAXB
     */
    protected ModifyResponseAccessor(ModifyResponseType response) {
        super(response, response.getPso());
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public ModifyResponseBuilder toBuilder() {
        return ResponseBuilder.builderForModify().fromResponse(this.response);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModifyResponseAccessor asAccessor(ModifyResponseType response) {
        return new ModifyResponseAccessor(response);
    }
    
}