/* 
 * Copyright (c) 2015 ricky <https://github.com/rickyepoderi/spml4jaxb>
 * 
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  See the file COPYING included with this distribution for more
 *  information.
 */
package es.rickyepoderi.spml4jaxb.accessor;

import es.rickyepoderi.spml4jaxb.builder.ResetPasswordResponseBuilder;
import es.rickyepoderi.spml4jaxb.builder.ResponseBuilder;
import es.rickyepoderi.spml4jaxb.msg.password.ResetPasswordResponseType;

/**
 * <p>Accessor for the SPMLv2 ResetPassword operation response. The ResetPassword
 * operation is defined inside the password capability (capability to perform
 * password management). This operation is used to change the password
 * without sending a new password, the system chooses one password and that
 * is returned in the response. The response contains the new password
 * selected and assigned by the system to the user if success.</p>
 * 
 * @author ricky
 */
public class ResetPasswordResponseAccessor extends BaseResponseAccessor<ResetPasswordResponseType, 
        ResetPasswordResponseAccessor, ResetPasswordResponseBuilder> {
    
    /**
     * Constructor for an empty reset password response accessor.
     */
    protected ResetPasswordResponseAccessor() {
        this(new ResetPasswordResponseType());
    }
    
    /**
     * Constructor for a reset password response accessor giving the internal type.
     * @param response The internal reset password response type as generated by JAXB
     */
    protected ResetPasswordResponseAccessor(ResetPasswordResponseType response) {
        super(response, null);
    }
    
    /**
     * Getter for the assgined password.
     * @return The assigned password or null
     */
    public String getPassword() {
        return response.getPassword();
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        String nl = System.getProperty("line.separator");
        StringBuilder sb = new StringBuilder(super.toString());
        sb.append("  password: ").append(getPassword() == null? "null":"********").append(nl);
        return sb.toString();
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public ResetPasswordResponseBuilder toBuilder() {
        return ResponseBuilder.builderForResetPassword().fromResponse(this.response);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResetPasswordResponseAccessor asAccessor(ResetPasswordResponseType response) {
        return new ResetPasswordResponseAccessor(response);
    }
}