/* 
 * Copyright (c) 2015 ricky <https://github.com/rickyepoderi/spml4jaxb>
 * 
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  See the file COPYING included with this distribution for more
 *  information.
 */
package es.rickyepoderi.spml4jaxb.accessor;

import es.rickyepoderi.spml4jaxb.builder.RequestBuilder;
import es.rickyepoderi.spml4jaxb.builder.ResponseBuilder;
import es.rickyepoderi.spml4jaxb.builder.ResumeRequestBuilder;
import es.rickyepoderi.spml4jaxb.msg.suspend.ResumeRequestType;
import java.util.Date;

/**
 * <p>Accessor for the SPMLv2 Resume operation request. The resume
 * operation is defined inside the suspend capability (capability to
 * enable and disable objects in the target). The resume operation
 * is used to enable an object previously disabled (suspended). The resume 
 * request besides the PSO identifier to resume can send the effective
 * date of the action (the date-time when the object will be resumed).</p>
 * 
 * @author ricky
 */
public class ResumeRequestAccessor extends BaseRequestAccessor<ResumeRequestType, ResumeRequestAccessor, ResumeRequestBuilder> {

    /**
     * Constructor for an empty resume request accessor.
     */
    protected ResumeRequestAccessor() {
        this(new ResumeRequestType());
    }
    
    /**
     * Constructor for a resume request accessor giving the internal type.
     * @param request The internal resume request type as generated by JAXB
     */
    protected ResumeRequestAccessor(ResumeRequestType request) {
        super(request, request.getPsoID(), null);
    }
    
    /**
     * Getter for the effective date when the object should be resumed.
     * @return The date or null
     */
    public Date getEffectiveDate() {
        if (request.getEffectiveDate() != null) {
            return request.getEffectiveDate().toGregorianCalendar().getTime();
        } else {
            return null;
        }
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public ResponseBuilder responseBuilder() {
        return ResponseBuilder.builderForResume();
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public ResumeRequestBuilder toBuilder() {
        return RequestBuilder.builderForResume().fromRequest(this.request);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResumeRequestAccessor asAccessor(ResumeRequestType request) {
        return new ResumeRequestAccessor(request);
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        String nl = System.getProperty("line.separator");
        StringBuilder sb = new StringBuilder(super.toString());
        sb.append("  effectiveDate: ").append(getEffectiveDate()).append(nl);
        return sb.toString();
    }
    
}