/* 
 * Copyright (c) 2015 ricky <https://github.com/rickyepoderi/spml4jaxb>
 * 
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  See the file COPYING included with this distribution for more
 *  information.
 */
package es.rickyepoderi.spml4jaxb.accessor;

import es.rickyepoderi.spml4jaxb.builder.ResponseBuilder;
import es.rickyepoderi.spml4jaxb.builder.ResumeResponseBuilder;
import es.rickyepoderi.spml4jaxb.msg.core.ResponseType;

/**
 * <p>Accessor for the SPMLv2 Resume operation response. The resume
 * operation is defined inside the suspend capability (capability to
 * enable and disable objects in the target). The resume operation
 * is used to enable an object previously disabled (suspended). The resume 
 * response has no special properties.<p>
 * 
 * @author ricky
 */
public class ResumeResponseAccessor extends BaseResponseAccessor<ResponseType, ResumeResponseAccessor, ResumeResponseBuilder> {

    /**
     * Constructor for a new and empty resume response request.
     */
    protected ResumeResponseAccessor() {
        this(new ResponseType());
    }
    
    /**
     * Constructor of a resume response accessor giving the internal type.
     * @param response The resume response type as specified in SPMLv2 and generated by JAXB
     */
    protected ResumeResponseAccessor(ResponseType response) {
        super(response, null);
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public ResumeResponseBuilder toBuilder() {
        return ResponseBuilder.builderForResume().fromResponse(this.response);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResumeResponseAccessor asAccessor(ResponseType response) {
        return new ResumeResponseAccessor(response);
    }
    
}
