/* 
 * Copyright (c) 2015 ricky <https://github.com/rickyepoderi/spml4jaxb>
 * 
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  See the file COPYING included with this distribution for more
 *  information.
 */
package es.rickyepoderi.spml4jaxb.accessor;

import es.rickyepoderi.spml4jaxb.builder.SchemaBuilder;
import es.rickyepoderi.spml4jaxb.client.SpmlException;
import es.rickyepoderi.spml4jaxb.msg.core.SchemaEntityRefType;
import es.rickyepoderi.spml4jaxb.msg.core.SchemaType;
import es.rickyepoderi.spml4jaxb.msg.spmldsml.AttributeDefinitionReferenceType;
import es.rickyepoderi.spml4jaxb.msg.spmldsml.AttributeDefinitionType;
import es.rickyepoderi.spml4jaxb.msg.spmldsml.ObjectClassDefinitionType;
import java.io.StringWriter;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.xml.bind.JAXBElement;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.DOMException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 * <p>Accessor for a schema that is returned inside a target in the ListTargets
 * response. The schema is quite different if the target is DSML or XSD 
 * profile. In a DSML profile the shema is a list of attribute definitions and
 * the objects the target manages. In XSD is just a XSD file that defines all
 * the XML objects the target handles. Both types of schemas return the
 * list of entities the target manages.</p>
 * 
 * @author ricky
 */
public class SchemaAccessor implements Accessor<SchemaType, SchemaAccessor, SchemaBuilder>{
    
    /**
     * The internal schema type generated by JAXB.
     */
    protected SchemaType schema;
    
    /**
     * Constructor using the internal schema type.
     * @param schema The schema type as generated by JAXB.
     */
    public SchemaAccessor(SchemaType schema) {
        this.schema = schema;
    }
    
    /**
     * The set of entity names the target manages.
     * @return The set of entity names 
     */
    public Set<String> getSupportedEntityNames() {
        Set<String> res = new HashSet<>();
        for (SchemaEntityRefType ref: schema.getSupportedSchemaEntity()) {
            res.add(ref.getEntityName());
        }
        return res;
    }
    
    /**
     * Check if a specific entity name is a container or not.
     * @param name The name of the entity
     * @return true if the entity is specified as a container, false if not
     */
    public boolean isEntityContainer(String name) {
        for (SchemaEntityRefType ref: schema.getSupportedSchemaEntity()) {
            if (name.equals(ref.getEntityName())) {
                return ref.isIsContainer() == null? false:ref.isIsContainer();
            }
        }
        return false;
    }
    
    /**
     * The schema can be specified in another file or reference. This method 
     * gets that reference.
     * @return The reference or null
     */
    public String getReference() {
        return schema.getRef();
    }
    
    /**
     * Getter for the first DSML schema defined in the accessor.
     * @return The first DSML schema defined or null
     */
    public es.rickyepoderi.spml4jaxb.msg.spmldsml.SchemaType getDsmlSchema() {
        List<Object> data = schema.getAny();
        for (Object o : data) {
            if (o instanceof es.rickyepoderi.spml4jaxb.msg.spmldsml.SchemaType) {
                return (es.rickyepoderi.spml4jaxb.msg.spmldsml.SchemaType) o;
            } else if (o instanceof JAXBElement) {
                if (((JAXBElement) o).getValue() instanceof es.rickyepoderi.spml4jaxb.msg.spmldsml.SchemaType) {
                    return (es.rickyepoderi.spml4jaxb.msg.spmldsml.SchemaType) ((JAXBElement) o).getValue();
                }
            }
        }
        return null;
    }
    
    /**
     * In a DSML profile the method return the attribute definitions that
     * the DSML schema defines.
     * @return The array of attribute definitions or empty array
     */
    public AttributeDefinitionType[] getDsmlAttributeDefinitions() {
        es.rickyepoderi.spml4jaxb.msg.spmldsml.SchemaType dsmlSchema = getDsmlSchema();
        if (dsmlSchema != null) {
            return dsmlSchema.getAttributeDefinition().toArray(new AttributeDefinitionType[0]);
        }
        return new AttributeDefinitionType[0];
    }
    
    /**
     * In a DSML profile the method returns the array of objectclass definitions
     * the target defines. 
     * @return The array of objectclass definitions or empty array
     */
    public ObjectClassDefinitionType[] getDsmlObjectClassDefinition() {
        es.rickyepoderi.spml4jaxb.msg.spmldsml.SchemaType dsmlSchema = getDsmlSchema();
        if (dsmlSchema != null) {
            return dsmlSchema.getObjectClassDefinition().toArray(new ObjectClassDefinitionType[0]);
        }
        return new ObjectClassDefinitionType[0];
    }
    
    /**
     * In a XSD profile this method returns the XSD schema file as a String.
     * @return The XSD schema or null
     * @throws SpmlException Some error reading the XSD definition
     */
    public String getXsdSchemaString() throws SpmlException {
        Document doc = getXsdSchemaDocument();
        if (doc != null) {
            try {
                TransformerFactory tFactory = TransformerFactory.newInstance();
                Transformer transformer = tFactory.newTransformer();
                DOMSource source = new DOMSource(doc);
                StringWriter sw = new StringWriter();
                transformer.transform(source, new StreamResult(sw));
                return sw.toString();
            } catch (TransformerException e) {
                throw new SpmlException(e);
            }
        }
        return null;
    }
    
    /**
     * In a XSD profile this method return the DOM document that corresponds
     * to the XSD schema file defined in the target.
     * @return The document that contains the XSD or null
     * @throws SpmlException Some error reading the XSD definition
     */
    public Document getXsdSchemaDocument() throws SpmlException {
        for (Object o : schema.getAny()) {
            if (o instanceof Element) {
                Element el = (Element) o;
                if ("http://www.w3.org/2001/XMLSchema".equals(el.getNamespaceURI())
                        && "schema".equals(el.getLocalName())) {
                    try {
                        Document doc = BaseRequestAccessor.documentBuilderFactory.newDocumentBuilder().newDocument();
                        doc.adoptNode(el);
                        doc.appendChild(el);
                        return doc;
                    } catch (DOMException|ParserConfigurationException e) {
                        throw new SpmlException(e);
                    }
                }
            }
        }
        return null;
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        String nl = System.getProperty("line.separator");
        StringBuilder sb = new StringBuilder("    Schema").append(nl)
                .append("      entities: ").append(getSupportedEntityNames()).append(nl)
                .append("      ref: ").append(getReference()).append(nl);
        if (getDsmlAttributeDefinitions() != null) {
            sb.append("      AttributeDefinitions:").append(nl);
            for (AttributeDefinitionType attr : getDsmlAttributeDefinitions()) {
                sb.append("        name: ").append(attr.getName())
                        .append(" type: ").append(attr.getType())
                        .append(" multi: ").append(attr.isMultivalued())
                        .append(" desc: ").append(attr.getDescription()).append(nl);
            }
        }
        if (getDsmlObjectClassDefinition() != null) {
            sb.append("      ObjectclassDefinitions:").append(nl);
            for (ObjectClassDefinitionType obj : getDsmlObjectClassDefinition()) {
                sb.append("        name: ").append(obj.getName())
                        .append(" desc: ").append(obj.getDescription()).append(nl);
                if (obj.getMemberAttributes() != null && obj.getMemberAttributes().getAttributeDefinitionReference() != null) {
                    for (AttributeDefinitionReferenceType def : obj.getMemberAttributes().getAttributeDefinitionReference()) {
                        sb.append("          name: ").append(def.getName())
                                .append(" schema: ").append(def.getSchema())
                                .append(" req: ").append(def.isRequired()).append(nl);
                    }
                }
            }
        }
        try {
            String xmlSchema = getXsdSchemaString();
            if (xmlSchema != null) {
                sb.append("      Schema:").append(nl).append(xmlSchema).append(nl);
            }
        } catch (SpmlException e) {
            // no-op
        }
        return sb.toString();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchemaType getInternalType() {
        return this.schema;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchemaBuilder toBuilder() {
        return new SchemaBuilder(this.schema, this.getDsmlSchema());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchemaAccessor asAccessor(SchemaType type) {
        return new SchemaAccessor(type);
    }
}
